gitlabEnv: ENC[AES256_GCM,data:J8aHT3FNEwxED2NbrBtAvMbBB4XlUTPZyf9j0TKjUhH8woZbIuf6QbF9coS0do2oTMPkd8i6hDnurAxy4erKwXtXp14TgA9YFmaL6LMXl0m6gi3ANbubU49B9w==,iv:FsYhjiKOQG/JkvzqERoq1S/ohXhBgnpEEwL1UaZJlXQ=,tag:zhK0bI48jf5kwh1pXdyZlQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1wz75gdvjhkntzakrfyprs8svhakcka7jgzgd9zkw2u9uef9ve97qn9078q
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlN3pTY2pEbWllQzhlUEVj
            Z2I3dmdjb3lZSHlBMzRPRU42RlkySmNNVEVvClRpRWhWOFFuRmtkRjc4WHVtVDVa
            aGVuZHN3OGV6NXJESlJPTnVoUmhxUHMKLS0tIGk4VC91UVlDQ2h4UjkrWVZYY1h4
            V3dscWRSdnhLa0EvQTBYRldQdXJSTVEKtvoHwRLPaIeMN0psn8Q5daaxcm+fqcFw
            FYw3UauQNWs8erPDE8XwWsfIIfTHMxFuRIEQyhFZAxnFptLu07/Icg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age17mn2rmzxum00ptd3adzumzu3qdkzmctwyvlaa24mu7phnwh2nafsnsngmq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUejhXMzliaXpXY1JsRDFO
            aUdTL29YdlNLaTRWa3YralVsbXVzN01rVzNJCnV2NUx4Z1JFUk1CTTllV2NMNEdp
            cTdSWVM4eW5QelREVlo1RHFuZWlrSUUKLS0tIFphMWlHVUdzSmZ3YW0razdDOGdk
            SWpxV1A1bkkxbk9MQW8vcHp5YXZYa3cKFrzcC81gMNdHKp9bWSKBQ/m01LRcouWU
            X7f/+5W7Pmru4IZz3/KQ2xuyZ2B70MvoJeSi6eI3JQWebQ8eAXJcCQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-03-16T09:39:07Z"
    mac: ENC[AES256_GCM,data:asgyhe3C6FPjg3xQZQm0yc87NLx0vRBJ9n42Zb4LIfxw9lDZXosaFBqCL4xfO+iJRI+6d5EYusXDLom2xM66BU34S8MdnwY1z6NqSiHUSUrn4kleD6yi8t0do0nbchqC5BgXqBwjcZUBCTc2PbmAY0uDlsSRkjadFm/obV83WDk=,iv:LJeN2jrHIkX5GxLJMVKSdiari5ro6/ktO6veHDMDsik=,tag:3915m7IZhg4KmBqwwY69OA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
