minioEnv: ENC[AES256_GCM,data:UolYM5xt3fn8Ozk4r8GYhJ/FGDpBUD4n/tKoASyjHtfWi0E8jl1B8X/2aoEoKcw6OJImALEGjlmQ0k9JR1G5xwSmL9sWjs9K+Jhqx0qj6iynr0Q0cg0/vdhN/rGEQ6FTT122UdinhchrwX73sNOO469dseVxNDWGnB/XGJJmQUjr8oKbPK0qplecxZq9KAyvbA4MnaBbs7XjJX0c7y1r,iv:FeeYOqYE12P3D55hBVPdY0SRyxt6KQlyUmBhJafYy0g=,tag:AFMJhxdbJyhkmPU8yU6S3w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1wz75gdvjhkntzakrfyprs8svhakcka7jgzgd9zkw2u9uef9ve97qn9078q
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaUnBRMHlHdDJOT0ZGQ3Mz
            WkphUjRMWkp4c1B0aERGVG4rSHNQQUMwSlYwClAwTXBtTENuRnhZc1J6SlhFUW1Y
            aFdzQUkxeTdnRGRXYjMxaXk4Rkt4K2MKLS0tIFdxTXV6Z05XS3hwOGJ2QW5BYW9C
            SmxRaGJjcFJieHZRdVV3em44bGZCenMKZE9jakg6Y8BXmEpkWRyaOrUFDt0cttdH
            UPlEDi5m3kkcP5t4h8aBLElkqqjIZzstxWC9wUV7KlOlLHqxkRS0OA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age17mn2rmzxum00ptd3adzumzu3qdkzmctwyvlaa24mu7phnwh2nafsnsngmq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzeEl4d05EQjJ3N0lWc3RM
            aFNvWHlWQXBlL1A2aHZQS3VoMzdyNHJ3Q0VrCmF5YnpKNGN2U1BhUithbzlMNWIw
            T3JiK0t5VTNrODR4T1RkT3EyME1xMTAKLS0tIE1rSzNGVnprNkdCc1NROGsxN0FE
            aXpOOUxuVnVHYkt3czR6SE5kRGFTeHMKEfDAOJUd7u326GdkbHUJOUbPx61lRQ1c
            U4lam2nChiNGTJZkAJP+1dgC3tAT0GZnhpBG2WjY9Fw6ha7tfDI1IA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-03-15T12:00:37Z"
    mac: ENC[AES256_GCM,data:yrwU5kVMtuKYmGij9PsdUUZbqOkfIImd6G0b0E6+EzCMJFrNzoRg+4vkvLeQSQFJlQDZbWs2os3ld+KSfavKn3fE0B7Xxwh7T3KiQIPLR/S1+ZQc7YkIt+1AAoahhoHWXkAkxy3sgnfXNyrD20LUyGVjw/m0/TFXSkqkbGo7kvo=,iv:hljO15gvSCmgaxNvW2VdF5hk05EMqtlekyrhBw+VbPI=,tag:r/ieHL0NVUsONrTI0MDd6Q==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
